#!/bin/sh
#PBS -N test
#PBS -l walltime=4:0:00
#PBS -l select=1:ncpus=32:mpiprocs=32
#PBS -A UCUB0167
#PBS -q main
#PBS -l job_priority=economy
#PBS -o exec.out
#PBS -e exec.err

module purge
module load ncarenv/23.06
module load intel/2023.0.0
module load openmpi/main

mpirun ./lesmpi > logfile.out
