#!/bin/sh
#PBS -N interactive-cpu
#PBS -l walltime=08:00:00
#PBS -l select=1:ncpus=32:mpiprocs=32
#PBS -A UCUB0166
#PBS -q main
#PBS -l job_priority=regular
#PBS -o exec.out
#PBS -e exec.err

module --force purge
module load ncarenv/23.06
module load intel/2023.0.0
module load openmpi/main

